### ISSUE TITLE
Blowflies example

### ISSUE THREAD

**Issue by slwu89** [kerguler/sPop2.jl#7]
Hi @kerguler, I'm planning to work out the case studies from your 1st sPop paper in F1000 in a notebook to showcase how to use Population.jl (and also for my own practice!) I started with the classic blowflies delay model in a notebook here (https://github.com/slwu89/Population.jl/blob/sciml/docs/case_studies.ipynb) but was getting incorrect results, if you have a moment could you help me check the code and see where I messed up?

**Comment by kerguler** [comment]
Hi @slwu89, I think the problem is in line 23 of the 3rd code block: `for (q,n) in out[m][3][1]`.
This one refers to the poptable of the first process, which is mortality. I think you need to access the second poptable: `out[m][3][2]`.
I included your code in the examples
[https://github.com/kerguler/Population.jl/blob/main/docs/blowflies.ipynb](https://github.com/kerguler/Population.jl/blob/main/docs/blowflies.ipynb)
I think, we should create a model repository in the docs (in .md/.html format) with a collection of useful models like this.

**Comment by slwu89** [comment]
Ah of course...thanks! I'll work out the rest of the case studies as I have time and submit a PR for them.

**Comment by slwu89** [comment]
closing with #8!
